swagger: '2.0'
info:
  version: '1.0'
  title: Introduction for Oauth2 SCA flow in XS2A
  description: >
    OAuth2 is an additional SCA flow for XS2A version 1.3.
    
    TPP can activate Oauth2 flow by providing 'TPP-Oauth2-Preferred: true' header in consent creation.


    Example curl for consent creation:


    ```
    
    curl --request POST \
      --url https://openbanking.api.tietoevry.com/sandbox/xs2a/v1.3/consents \
      --header 'Content-Type: application/json' \
      --header 'TPP-Explicit-Authorisation-Preferred: false' \
      --header 'TPP-Nok-Redirect-URI: https://estudijas.lu.lv' \
      --header 'TPP-Oauth2-Preferred: true' \
      --header 'TPP-Redirect-URI: https://google.com' \
      --header 'X-API-Key: fd5b57cb-48b4-409c-9dad-a76503f29dee' \
      --header 'X-Request-ID: 3edda6e1-1aaf-406b-aa26-d1229496178d' \
      --data '{
        "access":
        { 
            "transactions": []
        },
        "recurringIndicator":true,
        "validUntil": "2021-03-01",
        "frequencyPerDay": "100",
        "combinedServiceIndicator":false
    }'
    
    ```
    
    In return TPP receives “scaOAuth” link that points to OpenID Discovery link. 
    
    OpenID Discovery link is used to get information about OpenID endpoints, for example, authorization and token endpoints. 


    ```
    
    {
      "consentStatus": "received",
      "consentId": "6dbbc6bf-c249-4148-8ed9-943c88b3a951",
      "_links": {
        "self": {
          "href": "/sandbox/xs2a/v1.3/consents/6dbbc6bf-c249-4148-8ed9-943c88b3a951"
        },
        "status": {
          "href": "/sandbox/xs2a/v1.3/consents/6dbbc6bf-c249-4148-8ed9-943c88b3a951/status"
        },
        "scaOAuth": {
          "href": "https://openbanking.api.tietoevry.com/auth/realms/tieto-oauth2/.well-known/openid-configuration"
        }
      },
      "authorisationId": "b575dd67-6836-4d39-98bf-cb268c7ad771",
      "psuMessage": "Use Oauth2 configuration link to authorize PSU!"
    }
    
    ```
    
    Next actions in OAuth2 flow are:
    
    * Use authorization endpoint to authorize consent and get authorization code
      * client_id query parameter must be ‘’test-client’. Currently all TPPs use one Oauth2 public client. In future TPPs will be able to use OpenID Dynamic Registration endpoint to create a confidential OAuth2 client that will use client_id and client_secret parameters
    * scope query parameter must contain a variable in form: role:consentId. Accepted roles values are: AIS, PIS, PIIS.
      * redirect_uri query parameter still must be added even if redirect uri is specified in consent/auth-subresource creation. The parameter can be any value.
    * Use token endpoint to exchange the authorization code for access token and refresh token
    
    
    Example curl for authorization endpoint usage.


    ```
    
    curl --request GET \
      --url 'https://openbanking.api.tietoevry.com/auth/realms/tieto-oauth2/protocol/openid-connect/auth?client_id=test-client&response_type=code&scope=openid%20AIS%3Af9a14673-815b-4bbd-8f9a-bfd9b8adf779&redirect_uri=https%3A%2F%2Fgoogle.com' 
      
    ```
    
    Example curl for <b>access token</b> endpoint usage.


    ```
    
    curl --request POST \
      --url https://openbanking.api.tietoevry.com/auth/realms/tieto-oauth2/protocol/openid-connect/token \
      --header 'Content-Type: application/x-www-form-urlencoded'
      --data grant_type=authorization_code \
      --data code=eyJhbGciOiJkaXI…\
      --data client_id=test-client \
      --data redirect_uri=https://google.com
      
    ```
    
    The access token must be used in GET /accounts XS2A endpoint if consent has been authorized using OAuth2 flow. The access token must be added in Authorization header.
    
    
    Example curl for accounts endpoint:


    ```
    
    curl --request GET \
      --url https://openbanking.api.tietoevry.com/sandbox/xs2a/v1.3/accounts \
      --header 'Accept: application/json' \
      --header 'Authorization: Bearer eyJhbGciOiJSU………………………………………..kzwjWLsXT8njoQ' \
      --header 'X-API-Key: fd5b57cb-48b4-409c-9dad-a76503f29dee' \
      --header 'X-Request-ID: a1cef9f9-f3da-408b-aaa0-5ad2a7ff23ec' \
      --header 'consent-ID: afaa1e32-87f8-4335-a63c-a69448d10830' 

    ```
    
    <lu></lu>
    <lu></lu>
   
    If the access token has expired there is a possibility to use refresh token. From the same result, using refresh_token string


    Example curl for <b>refresh token</b> endpoint usage.


    ```
    
    curl --request POST \
      --url https://openbanking.api.tietoevry.com/auth/realms/tieto-oauth2/protocol/openid-connect/token \
      --header 'Content-Type: application/x-www-form-urlencoded'
      --data grant_type=refresh_token \
      --data refresh_token=ryJhbGciOiJkuZI………\
      --data client_id=test-client \

      
    ```
    
    The again new access token must be used in GET /accounts XS2A endpoint if consent has been authorized using OAuth2 flow. The access token must be added in Authorization header.
    
    
    Example curl for accounts endpoint:


    ```
    
    curl --request GET \
      --url https://openbanking.api.tietoevry.com/sandbox/xs2a/v1.3/accounts \
      --header 'Accept: application/json' \
      --header 'Authorization: Bearer byJwbGeiOiJSU………………………………………..RzwjWAsUZ8nroE' \
      --header 'X-API-Key: fd5b57cb-48b4-409c-9dad-a76503f29dee' \
      --header 'X-Request-ID: v4cef9f9-f9aa-408b-aaa0-5ad2a7ff25us' \
      --header 'consent-ID: woaa1e32-45f8-4335-a63c-a69448d10821' 

    ```
paths: {}
