# x-archived-from: tietoevry-tieto-oauth2-embedded-intro.yaml
# x-archived-on: 2026-09-16
swagger: '2.0'
info:
  version: '1.0'
  title: Introduction for Embedded SCA flow
  description: >
    Embedded SCA flow is an additional SCA flow for XS2A version 1.3.

    TPP must start the embedded SCA flow by acquiring PSU authentication in Oauth2 pre-step.

    * Use authorization endpoint to authorize consent and get authorization code

    * client_id query parameter must be ‘’test-client’. Currently all TPPs use one Oauth2 public client. In future TPPs will be able to use OpenID Dynamic Registration endpoint to create a confidential OAuth2 client that will use client_id and client_secret parameters

    * scope query parameter must be 'PSU'

    * Use token endpoint to exchange the authorization code for access token and refresh token


    Example curl for OAuth2 PSU pre-step request:

    ```

    curl --request GET \
      --url 'https://openbanking.api.tietoevry.com/auth/realms/tieto-oauth2/protocol/openid-connect/auth?client_id=test-client&response_type=code&scope=openid%20PSU&redirect_uri=https%3A%2F%2Fgoogle.com'

    ```


    Example curl for token endpoint usage.


    ```

    curl --request POST \
      --url https://openbanking.api.tietoevry.com/auth/realms/tieto-oauth2/protocol/openid-connect/token \
      --header 'Content-Type: application/x-www-form-urlencoded'
      --data grant_type=authorization_code \
      --data code=eyJhbGciOiJkaXI…\
      --data client_id=test-client \
      --data redirect_uri=https://google.com

    ```

    After acquiring the PSU pre-step token, TPP can create account information consent with the pre-step token in
    'Authorization' header and 'TPP-Redirect-Preferred' header set to 'false'.
    'TPP-Redirect-Preferred' header's 'false' value indicates to Open Banking that TPP prefers Embedded SCA flow.


    Example curl for consent creation:


    ```
    
    curl --request POST \
      --url https://openbanking.api.tietoevry.com/sandbox/xs2a/v1.3/consents \
      --header 'Content-Type: application/json' \
      --header 'TPP-Explicit-Authorisation-Preferred: false' \
      --header 'TPP-Nok-Redirect-URI: https://estudijas.lu.lv' \
      --header 'Authorization: Bearer fljgdlfgjdf....' \
      --header 'TPP-Redirect-Preferred: false' \
      --header 'X-API-Key: fd5b57cb-48b4-409c-9dad-a76503f29dee' \
      --header 'X-Request-ID: 3edda6e1-1aaf-406b-aa26-d1229496178d' \
      --data '{
        "access":
        { 
            "transactions": []
        },
        "recurringIndicator":true,
        "validUntil": "2022-12-01",
        "frequencyPerDay": "100",
        "combinedServiceIndicator":false
    }'
    
    ```
    
    In return TPP receives information about the OTP mechanism used in the Embedded SCA flow.
    Tietoevry Open Banking in the example Embedded SCA flow uses a hardcoded OTP value: 12345.


    ```
    
    {
      "consentStatus": "received",
      "consentId": "b71ff...fed",
      "_links": {
        "self": {
          "href": "/sandbox/xs2a/v1.3/consents/b71ff...fed"
        },
        "status": {
          "href": "/sandbox/xs2a/v1.3/consents/b71ff...fed/status"
        }
      },
      "authorisationId": "5ae...1c8",
      "chosenScaMethod": {
        "authenticationType": "PUSH_OTP",
        "name": "Hardcoded code: 12345"
      },
      "challengeData": {
        "otpMaxLength": "5",
        "otpFormat": "integer"
      }
    }
    
    ```

    Next step for TPP is to enter the hardcoded OTP value to the XS2A interface by using 'Transaction authorisation' call.
    The call must include PSU pre-step token in Authorization header and "scaAuthenticationData" parameter in request body
    with value '12345'.


    Example of the 'Transaction authorisation' call:


    ```

    curl --request PUT \
      --url https://openbanking.api.tietoevry.com/sandbox/xs2a/v1.3/consents/b71ff...fed/authorisations/5ae...1c8 \
      --header 'Content-Type: application/json' \
      --header 'Authorization: Bearer fljgdlfgjdf....' \
      --header 'X-API-Key: fd5b57cb-48b4-409c-9dad-a76503f29dee' \
      --header 'X-Request-ID: 3edda6e1-1aaf-406b-aa26-d1229496178d' \
      --data '{
        "scaAuthenticationData": "12345"
    }'

    ```


    In response TPP receives the sca status.


    Example of the response:

    ```

    {
      "scaStatus": "finalised"
    }

    ```


    If TPP receives "finalised" status, then TPP can assume that account information consent is also approved and TPP
    can successfully get account information.
    
    Example curl for accounts endpoint:


    ```
    
    curl --request GET \
      --url https://openbanking.api.tieto.com/sandbox/xs2a/v1.3/accounts \
      --header 'Accept: application/json' \
      --header 'X-API-Key: fd5b57cb-48b4-409c-9dad-a76503f29dee' \
      --header 'X-Request-ID: a1cef9f9-f3da-408b-aaa0-5ad2a7ff23ec' \
      --header 'consent-ID: b71ff...fed'

    ```
paths: {}
